name: Deploy Terraform to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_AC }}
        aws-secret-access-key: ${{ secrets.AWS_SEC }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Install Git LFS
      run: |
        sudo apt-get install git-lfs
        git lfs install
        git lfs pull

    - name: Terraform Init
      run: cd AWS/ ; terraform init

    #- name: Terraform Apply
      #run: cd AWS/ ; terraform apply -auto-approve

    - name: Terraform Plan (Destroy Preview)
      run: cd AWS/ ; terraform plan -destroy

    - name: Terraform Destroy
      run: cd AWS/ ; terraform destroy -auto-approve
